services:
  - type: web
    name: teahousevilla
    env: python
    plan: free
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
