# Generated by Django 6.1 on 2026-08-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Leave blank to use the phone number.', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contacted', models.BooleanField(default=False, help_text='Mark once the owner has followed up with the guest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Booking Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
