# Generated by Django 6.1 on 2026-08-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_property_airbnb_url_property_booking_com_url"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("airbnb", "Airbnb"), ("booking_com", "Booking.com"), ("direct", "Direct Website"), ("manual", "Manual Block")], default="manual", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("villa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="availability_blocks", to="property.property")),
            ],
            options={
                "verbose_name_plural": "Availability Blocks",
                "ordering": ["start_date", "end_date"],
            },
        ),
        migrations.CreateModel(
            name="OTAAvailabilitySyncStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("airbnb", "Airbnb"), ("booking_com", "Booking.com")], max_length=20)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("success", "Synced"), ("failed", "Failed")], default="pending", max_length=20)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("villa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ota_sync_status", to="property.property")),
            ],
            options={
                "verbose_name_plural": "OTA Sync Status",
                "unique_together": {("villa", "source")},
            },
        ),
    ]
