# Generated by Django 6.1 on 2026-09-03 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_lifecycle'),
        ('property', '0003_property_airbnb_url_property_booking_com_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('AIRBNB', 'Airbnb'), ('BOOKING_COM', 'Booking.com')], max_length=20)),
                ('ical_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_syncs', to='property.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('villa', 'platform'), name='unique_calendar_sync_platform')],
            },
        ),
        migrations.CreateModel(
            name='ExternalCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('AIRBNB', 'Airbnb'), ('BOOKING_COM', 'Booking.com')], max_length=20)),
                ('external_event_id', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_calendar_events', to='property.property')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
                'constraints': [models.UniqueConstraint(fields=('villa', 'platform', 'external_event_id'), name='unique_external_calendar_event')],
            },
        ),
    ]
