# Generated by Django 6.1 on 2026-08-11 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='bi-check2-circle', help_text="Bootstrap Icons class name, e.g. 'bi-wifi'.", max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Teahouse Villa', max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Used on the homepage and in search/social previews.')),
                ('full_description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_maps_url', models.URLField(blank=True, help_text="Link used for the 'Get Directions' button.")),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Embed src URL for the map iframe.')),
                ('max_guests', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('property_size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, digits only, e.g. 94771234567', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('starting_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Used on the homepage if no active Price rows are configured.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('standard', 'Standard Rate'), ('weekend', 'Weekend Rate'), ('peak', 'Peak Season Rate'), ('off_season', 'Off-Season Rate'), ('special_offer', 'Special Offer')], default='standard', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Leave blank for the standard, always-on rate.', null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Prices',
                'ordering': ['price_type', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Maximum guests in this room.')),
                ('bed_type', models.CharField(blank=True, max_length=100)),
                ('bathroom_info', models.CharField(blank=True, max_length=150)),
                ('has_ac', models.BooleanField(default=True)),
                ('size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('facilities', models.ManyToManyField(blank=True, related_name='rooms', to='property.facility')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='property.property')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('villa', 'Villa'), ('bedrooms', 'Bedrooms'), ('bathrooms', 'Bathrooms'), ('pool', 'Swimming Pool'), ('kitchen', 'Kitchen'), ('garden', 'Garden'), ('exterior', 'Exterior'), ('nearby', 'Nearby Attractions')], default='villa', max_length=20)),
                ('is_cover', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='property.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='property.room')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
