# Generated by Django 6.1 on 2026-08-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube/Vimeo URL for an ambient video hero background. If blank, the hero shows an auto-sliding photo gallery instead.'),
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('restaurant', 'Restaurant'), ('landmark', 'Landmark'), ('activity', 'Activity'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20)),
                ('distance_text', models.CharField(help_text="e.g. '8 km' or '15 min drive'.", max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('google_maps_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='property.property')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('review_text', models.TextField()),
                ('source', models.CharField(choices=[('google', 'Google Reviews'), ('airbnb', 'Airbnb'), ('booking_com', 'Booking.com'), ('direct', 'Direct Guest'), ('other', 'Other')], default='google', max_length=20)),
                ('stay_date', models.DateField(blank=True, null=True)),
                ('guest_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='property.property')),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
    ]
