# Generated by Django 6.1 on 2026-08-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_hero_video_url_attraction_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airbnb_url',
            field=models.URLField(blank=True, help_text='Link to the Airbnb listing, if any.'),
        ),
        migrations.AddField(
            model_name='property',
            name='booking_com_url',
            field=models.URLField(blank=True, help_text='Link to the Booking.com listing, if any.'),
        ),
    ]
