# Generated by Django 6.1 on 2026-09-20 15:29

import django.db.models.deletion
import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_property_airbnb_url_property_booking_com_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("queen", "Queen"),
                            ("double", "Double"),
                            ("twin", "Twin"),
                            ("bunk", "Bunk"),
                            ("sofa", "Sofa Bed"),
                            ("crib", "Crib"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Social media preview image. Recommended: 1200x630px",
                null=True,
                upload_to="og/",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_canonical_url",
            field=models.URLField(
                blank=True, help_text="Canonical URL. Leave blank for auto-generation."
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_description",
            field=models.CharField(
                blank=True,
                help_text="Used in search results. Leave blank to auto-generate.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Used in search results and social media. Leave blank to auto-generate.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="google_maps_embed_url",
            field=property.models.GoogleMapsEmbedURLField(
                blank=True,
                help_text="Embed src URL for the map iframe.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="bed_type",
            field=models.CharField(
                blank=True,
                help_text="Legacy field. Use BedConfiguration for detailed configuration.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="PropertyAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Amenities"),
                            ("kitchen", "Kitchen"),
                            ("bathroom", "Bathroom"),
                            ("bedroom", "Bedroom"),
                            ("outdoor", "Outdoor"),
                            ("entertainment", "Entertainment"),
                            ("comfort", "Comfort & Convenience"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="bi-check2-circle",
                        help_text="Bootstrap Icons class name, e.g. 'bi-wifi'.",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for villa-wide amenities.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="property.room",
                    ),
                ),
                (
                    "villa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BedConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_configurations",
                        to="property.room",
                    ),
                ),
                (
                    "bed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="property.bedtype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "bed_type__display_order"],
                "unique_together": {("room", "bed_type")},
            },
        ),
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("garden", "Garden View"),
                            ("pool", "Pool View"),
                            ("mountain", "Mountain View"),
                            ("countryside", "Countryside View"),
                            ("landmark", "Landmark View"),
                            ("courtyard", "Inner Courtyard View"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "villa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("villa", "view_type")},
            },
        ),
    ]
